### ISSUE TITLE
http://server.sugarizer.org/  page optimization

### ISSUE THREAD

**Issue by Saichethan** [sugarlabs/sugarizer#3]
![36217066-82afd68e-11d6-11e8-9643-eab8d88adc5a](https://user-images.githubusercontent.com/34788026/36302396-4f871c96-132e-11e8-8acd-b4c9bd0237a9.png)
![36217036-6a0d746a-11d6-11e8-8d70-da591f2e145e](https://user-images.githubusercontent.com/34788026/36302403-583d790c-132e-11e8-937d-5637623233ac.png)

**Comment by samswag** [comment]
Did you try testing out what the site is for? That is a web version of "sugar" you don't expect it to work.

**Comment by samswag** [comment]
You can close this issue after testing.
